name:          saml2-web-sso
version:       '0.1'
synopsis:      'Library and example web app for the SAML Web-based SSO profile.'
author:        Wire Swiss GmbH
maintainer:    Wire Swiss GmbH <backend@wire.com>
copyright:     (c) 2017 Wire Swiss GmbH
license:       AGPL-3
license-file:  LICENSE
category:      System
description:   'See README.md'

ghc-options: -j -O2 -Wall -Wno-redundant-constraints -fwarn-tabs -Werror

dependencies:
  - base

  - aeson
  - base64-bytestring
  - containers
  - errors
  - exceptions
  - http-media
  - http-types
  - microlens
  - microlens-th
  - mtl
  - network-uri
  - servant
  - servant-multipart
  - servant-server
  - string-conversions
  - text
  - time
  - uri-bytestring
  - uuid
  - wai
  - warp
  - xml-conduit
  - xml-conduit-writer
  - xml-hamlet
  - xml-types
  - yaml
  - filepath

  # temporary, for debugging & dev
  - hsaml2
  - hxt
  - pretty-show

library:
  source-dirs:
    - src
  include-dirs:
    - src

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
    include-dirs:
      - src
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - saml2-web-sso

      - hedgehog
      - pretty-show
      - process
      - tasty
      - tasty-expected-failure
      - tasty-hunit
      - tasty-quickcheck
      - temporary
      - uniplate

executables:
  toy-sp:
    main: Main.hs
    source-dirs: toy-sp
    dependencies:
      - saml2-web-sso
