resolver: lts-11.4

packages:
- .
- location:
    git: https://github.com/wireapp/hsaml2
    commit: 60cbde9805bfc6a39d8064ad323c4a009bbc6187
  extra-dep: true

extra-deps:
- servant-multipart-0.11.1
- invertible-hxt-0.1  # for hsaml2
