resolver: lts-11.1

packages:
- .
- location:
    git: https://github.com/wireapp/hsaml2
    commit: 9d02d0b6c7747f25d53a617c27600beec6ec6392
  extra-dep: true

extra-deps:
- invertible-hxt-0.1  # for hsaml2
